In [160]:
import pandas
import math

In [161]:
import numpy as np
import os
from scipy import io

In [162]:
# def read_matFile(file):
#     mat = io.loadmat(file)
#     return mat

In [163]:
# mat = read_matFile("/home/ljzhou/zhangfan/PDVC_ShuJu/WorkoutUOW-18-skeleton/a001_s001_e001.mat")

In [164]:
mat = io.loadmat("E:\GitProjects\Video-Captioning\PDVC数据处理\WorkoutUOW-18-skeleton\\a001_s001_e001.mat")

In [165]:
print(mat)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Oct 29 18:17:16 2019', '__version__': '1.0', '__globals__': [], 'one_sample': array([[-4.43254458e-03,  6.26969635e-02,  3.07751274e+00, ...,
         1.19806148e-01, -7.38110483e-01,  3.10789037e+00],
       [-1.86426775e-03,  6.23902455e-02,  3.07780027e+00, ...,
         1.19443282e-01, -7.39387155e-01,  3.10847569e+00],
       [ 5.21074631e-04,  6.25513270e-02,  3.07817936e+00, ...,
         1.20068751e-01, -7.41531968e-01,  3.10954523e+00],
       ...,
       [-5.61582074e-02,  5.32767400e-02,  3.05065727e+00, ...,
         1.10598259e-01, -7.32131541e-01,  3.10978627e+00],
       [-5.48236482e-02,  5.34168333e-02,  3.04868913e+00, ...,
         1.10811770e-01, -7.32616305e-01,  3.10978365e+00],
       [-5.16514257e-02,  5.28396145e-02,  3.04643106e+00, ...,
         1.11337095e-01, -7.36358404e-01,  3.10856867e+00]])}


In [166]:
mat = mat['one_sample']

In [167]:
folder_path = "E:\GitProjects\Video-Captioning\PDVC数据处理\WorkoutUOW-18-skeleton"

In [168]:
mat.shape

(135, 60)

In [169]:
mat_list = os.listdir(folder_path) 

In [170]:
mat_list

['a001_s001_e001.mat',
 'a001_s001_e002.mat',
 'a001_s001_e003.mat',
 'a001_s001_e004.mat',
 'a001_s001_e005.mat',
 'a001_s001_e006.mat',
 'a001_s002_e001.mat',
 'a001_s002_e002.mat',
 'a001_s002_e003.mat',
 'a001_s002_e004.mat',
 'a001_s002_e005.mat',
 'a001_s002_e006.mat',
 'a001_s003_e001.mat',
 'a001_s003_e002.mat',
 'a001_s003_e003.mat',
 'a001_s003_e004.mat',
 'a001_s003_e005.mat',
 'a001_s003_e006.mat',
 'a001_s004_e001.mat',
 'a001_s004_e002.mat',
 'a001_s004_e003.mat',
 'a001_s004_e004.mat',
 'a001_s004_e005.mat',
 'a001_s004_e006.mat',
 'a001_s005_e001.mat',
 'a001_s005_e002.mat',
 'a001_s005_e003.mat',
 'a001_s005_e004.mat',
 'a001_s005_e005.mat',
 'a001_s005_e006.mat',
 'a001_s006_e001.mat',
 'a001_s006_e002.mat',
 'a001_s006_e003.mat',
 'a001_s006_e004.mat',
 'a001_s006_e005.mat',
 'a001_s006_e006.mat',
 'a001_s007_e001.mat',
 'a001_s007_e002.mat',
 'a001_s007_e003.mat',
 'a001_s007_e004.mat',
 'a001_s007_e005.mat',
 'a001_s007_e006.mat',
 'a001_s008_e001.mat',
 'a001_s008

In [171]:
matFileName1 = "a0"
matFileName2 = "s00"
matFileName3 = "e00" 

In [172]:
# for i in range(18):
#     for j in range(15):
#         for k in range(6):
#             if(i<10):
#                 matFileName1+="0"
#             matFileName1 = matFileName1 + str(i) + "_"
#             matFileName2 = matFileName2 + str(j) + "_"
#             matFileName3 = matFileName3 + str(k) + ".mat"
#             matFileName = os.path.join(matFileName1,matFileName2,matFileName3)

In [173]:
import pandas as pd

In [174]:
mat_tabel = pd.read_excel("./data_split.xlsx")

In [175]:
mat_tabel

ID  events  duration  Start  Seg 1  Seg 2  Seg 3  Seg 4  \
0     a001_s001_e001.mp4       5       9.0      0    0.0    2.0    2.0    7.0   
1     a001_s001_e002.mp4       5      11.0      0    0.0    1.0    2.5    7.0   
2     a001_s001_e003.mp4       5       9.0      0    0.0    1.0    2.0    7.0   
3     a001_s001_e004.mp4       5      11.0      0    1.0    2.5    6.0   10.0   
4     a001_s001_e005.mp4       5       9.0      0    0.0    1.0    3.0    7.0   
...                  ...     ...       ...    ...    ...    ...    ...    ...   
1507  a018_s014_e002.mp4       5      11.0      0    1.0    3.0    5.0    8.0   
1508  a018_s014_e003.mp4       5      11.0      0    1.0    3.0    5.0    7.5   
1509  a018_s014_e004.mp4       5      10.0      0    1.0    2.5    4.0    6.5   
1510  a018_s014_e005.mp4       5       8.0      0    0.0    1.5    3.0    6.0   
1511  a018_s014_e006.mp4       5       9.0      0    0.0    1.5    3.0    6.0   

      Seg 5  Seg 6  Seg 7  Unnamed: 11  Unnamed: 12  
0       9.0    0.0      0          NaN          NaN  
1      11.0    0.0      0          NaN          NaN  
2       9.0    0.0      0          NaN          NaN  
3      11.0    0.0      0          NaN          NaN  
4       9.0    0.0      0          NaN          NaN  
...     ...    ...    ...          ...          ...  
1507   11.0    0.0      0          NaN          NaN  
1508   11.0    0.0      0          NaN          NaN  
1509   10.0    0.0      0          NaN          NaN  
1510    8.0    0.0      0          NaN          NaN  
1511    9.0    0.0      0          NaN          NaN  

[1512 rows x 13 columns]

In [176]:
mat_tabel[['Seg 1','Seg 2','Seg 3','Seg 4','Seg 5','Seg 6']]

Seg 1  Seg 2  Seg 3  Seg 4  Seg 5  Seg 6
0       0.0    2.0    2.0    7.0    9.0    0.0
1       0.0    1.0    2.5    7.0   11.0    0.0
2       0.0    1.0    2.0    7.0    9.0    0.0
3       1.0    2.5    6.0   10.0   11.0    0.0
4       0.0    1.0    3.0    7.0    9.0    0.0
...     ...    ...    ...    ...    ...    ...
1507    1.0    3.0    5.0    8.0   11.0    0.0
1508    1.0    3.0    5.0    7.5   11.0    0.0
1509    1.0    2.5    4.0    6.5   10.0    0.0
1510    0.0    1.5    3.0    6.0    8.0    0.0
1511    0.0    1.5    3.0    6.0    9.0    0.0

[1512 rows x 6 columns]

In [177]:
mat_tabel.columns

Index(['ID', 'events', 'duration', 'Start', 'Seg 1', 'Seg 2', 'Seg 3', 'Seg 4',
       'Seg 5', 'Seg 6', 'Seg 7', 'Unnamed: 11', 'Unnamed: 12'],
      dtype='object')

In [178]:
mat_tabel = mat_tabel[['Seg 1','Seg 2','Seg 3','Seg 4','Seg 5','Seg 6','Seg 7']]

In [179]:
mat_tabel

Seg 1  Seg 2  Seg 3  Seg 4  Seg 5  Seg 6  Seg 7
0       0.0    2.0    2.0    7.0    9.0    0.0      0
1       0.0    1.0    2.5    7.0   11.0    0.0      0
2       0.0    1.0    2.0    7.0    9.0    0.0      0
3       1.0    2.5    6.0   10.0   11.0    0.0      0
4       0.0    1.0    3.0    7.0    9.0    0.0      0
...     ...    ...    ...    ...    ...    ...    ...
1507    1.0    3.0    5.0    8.0   11.0    0.0      0
1508    1.0    3.0    5.0    7.5   11.0    0.0      0
1509    1.0    2.5    4.0    6.5   10.0    0.0      0
1510    0.0    1.5    3.0    6.0    8.0    0.0      0
1511    0.0    1.5    3.0    6.0    9.0    0.0      0

[1512 rows x 7 columns]

In [180]:
mat_tabel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Seg 1   1512 non-null   float64
 1   Seg 2   1512 non-null   float64
 2   Seg 3   1512 non-null   float64
 3   Seg 4   1512 non-null   float64
 4   Seg 5   1512 non-null   float64
 5   Seg 6   1512 non-null   float64
 6   Seg 7   1512 non-null   int64  
dtypes: float64(6), int64(1)
memory usage: 82.8 KB


In [181]:
mat_numpy = mat_tabel.to_numpy()

In [182]:
mat_numpy

array([[ 0. ,  2. ,  2. , ...,  9. ,  0. ,  0. ],
       [ 0. ,  1. ,  2.5, ..., 11. ,  0. ,  0. ],
       [ 0. ,  1. ,  2. , ...,  9. ,  0. ,  0. ],
       ...,
       [ 1. ,  2.5,  4. , ..., 10. ,  0. ,  0. ],
       [ 0. ,  1.5,  3. , ...,  8. ,  0. ,  0. ],
       [ 0. ,  1.5,  3. , ...,  9. ,  0. ,  0. ]])

In [183]:
mat_numpy.shape

(1512, 7)

In [184]:
# start to end 二维数组
start_to_end_numpy = np.zeros((len(mat_numpy),2))

In [185]:
start_to_end_numpy

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [186]:
for i in range(len(mat_numpy)):
    start_to_end_numpy[i][0] = mat_numpy[i][0]
    k = 6
    while(k>=0 and mat_numpy[i][k]==0):
        k = k - 1   
    if(k==0):
        start_to_end_numpy[i][1] = mat_numpy[i][0]
    else:
        start_to_end_numpy[i][1] = mat_numpy[i][k-1]

In [187]:
start_to_end_numpy

array([[0. , 7. ],
       [0. , 7. ],
       [0. , 7. ],
       ...,
       [1. , 6.5],
       [0. , 6. ],
       [0. , 6. ]])

In [188]:
start_to_end_pandas = pd.DataFrame(start_to_end_numpy)

In [189]:
start_to_end_pandas

0     1
0     0.0   7.0
1     0.0   7.0
2     0.0   7.0
3     1.0  10.0
4     0.0   7.0
...   ...   ...
1507  1.0   8.0
1508  1.0   7.5
1509  1.0   6.5
1510  0.0   6.0
1511  0.0   6.0

[1512 rows x 2 columns]

In [190]:
start_to_end_pandas.isna().sum()

0    0
1    0
dtype: int64

In [191]:
start_to_end_pandas.fillna(axis=0,method='ffill')

0     1
0     0.0   7.0
1     0.0   7.0
2     0.0   7.0
3     1.0  10.0
4     0.0   7.0
...   ...   ...
1507  1.0   8.0
1508  1.0   7.5
1509  1.0   6.5
1510  0.0   6.0
1511  0.0   6.0

[1512 rows x 2 columns]

In [192]:
start_to_end_pandas.isnull().sum()

0    0
1    0
dtype: int64

In [193]:
for i in range(len(start_to_end_numpy)):
    start_to_end_numpy[i][0] = math.floor(start_to_end_numpy[i][0])
    start_to_end_numpy[i][1] = math.floor(start_to_end_numpy[i][1])

In [205]:
num_frame_numpy = np.zeros((len(start_to_end_numpy),2))

In [206]:
num_frame_numpy

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [209]:
for i in range(len(start_to_end_numpy)):
    num_frame_numpy[i][0] = start_to_end_numpy[i][0] * 15
    num_frame_numpy[i][1] = start_to_end_numpy[i][1] * 15   

In [210]:
num_frame_numpy

array([[  0., 105.],
       [  0., 105.],
       [  0., 105.],
       ...,
       [ 15.,  90.],
       [  0.,  90.],
       [  0.,  90.]])