In [195]:
import pandas
import math

In [196]:
import numpy as np
import os
from scipy import io

In [197]:
# def read_matFile(file):
#     mat = io.loadmat(file)
#     return mat

In [198]:
# mat = read_matFile("/home/ljzhou/zhangfan/PDVC_ShuJu/WorkoutUOW-18-skeleton/a001_s001_e001.mat")

In [199]:
mat = io.loadmat("E:\GitProjects\Video-Captioning\PDVC数据处理\WorkoutUOW-18-skeleton\\a001_s001_e001.mat")

In [200]:
print(mat)

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Oct 29 18:17:16 2019', '__version__': '1.0', '__globals__': [], 'one_sample': array([[-4.43254458e-03,  6.26969635e-02,  3.07751274e+00, ...,
         1.19806148e-01, -7.38110483e-01,  3.10789037e+00],
       [-1.86426775e-03,  6.23902455e-02,  3.07780027e+00, ...,
         1.19443282e-01, -7.39387155e-01,  3.10847569e+00],
       [ 5.21074631e-04,  6.25513270e-02,  3.07817936e+00, ...,
         1.20068751e-01, -7.41531968e-01,  3.10954523e+00],
       ...,
       [-5.61582074e-02,  5.32767400e-02,  3.05065727e+00, ...,
         1.10598259e-01, -7.32131541e-01,  3.10978627e+00],
       [-5.48236482e-02,  5.34168333e-02,  3.04868913e+00, ...,
         1.10811770e-01, -7.32616305e-01,  3.10978365e+00],
       [-5.16514257e-02,  5.28396145e-02,  3.04643106e+00, ...,
         1.11337095e-01, -7.36358404e-01,  3.10856867e+00]])}


In [201]:
mat = mat['one_sample']

In [202]:
folder_path = "E:\GitProjects\Video-Captioning\PDVC数据处理\WorkoutUOW-18-skeleton"

In [203]:
mat.shape

(135, 60)

In [204]:
mat_list = os.listdir(folder_path) 

In [205]:
mat_list

['a001_s001_e001.mat',
 'a001_s001_e002.mat',
 'a001_s001_e003.mat',
 'a001_s001_e004.mat',
 'a001_s001_e005.mat',
 'a001_s001_e006.mat',
 'a001_s002_e001.mat',
 'a001_s002_e002.mat',
 'a001_s002_e003.mat',
 'a001_s002_e004.mat',
 'a001_s002_e005.mat',
 'a001_s002_e006.mat',
 'a001_s003_e001.mat',
 'a001_s003_e002.mat',
 'a001_s003_e003.mat',
 'a001_s003_e004.mat',
 'a001_s003_e005.mat',
 'a001_s003_e006.mat',
 'a001_s004_e001.mat',
 'a001_s004_e002.mat',
 'a001_s004_e003.mat',
 'a001_s004_e004.mat',
 'a001_s004_e005.mat',
 'a001_s004_e006.mat',
 'a001_s005_e001.mat',
 'a001_s005_e002.mat',
 'a001_s005_e003.mat',
 'a001_s005_e004.mat',
 'a001_s005_e005.mat',
 'a001_s005_e006.mat',
 'a001_s006_e001.mat',
 'a001_s006_e002.mat',
 'a001_s006_e003.mat',
 'a001_s006_e004.mat',
 'a001_s006_e005.mat',
 'a001_s006_e006.mat',
 'a001_s007_e001.mat',
 'a001_s007_e002.mat',
 'a001_s007_e003.mat',
 'a001_s007_e004.mat',
 'a001_s007_e005.mat',
 'a001_s007_e006.mat',
 'a001_s008_e001.mat',
 'a001_s008

In [206]:
matFileName1 = "a0"
matFileName2 = "s00"
matFileName3 = "e00" 

In [207]:
# for i in range(18):
#     for j in range(15):
#         for k in range(6):
#             if(i<10):
#                 matFileName1+="0"
#             matFileName1 = matFileName1 + str(i) + "_"
#             matFileName2 = matFileName2 + str(j) + "_"
#             matFileName3 = matFileName3 + str(k) + ".mat"
#             matFileName = os.path.join(matFileName1,matFileName2,matFileName3)

In [208]:
import pandas as pd

In [209]:
mat_tabel = pd.read_excel("./data_split.xlsx")

In [210]:
mat_tabel

ID  events  duration  Start  Seg 1  Seg 2  Seg 3  Seg 4  \
0     a001_s001_e001.mp4       5       9.0      0    0.0    2.0    2.0    7.0   
1     a001_s001_e002.mp4       5      11.0      0    0.0    1.0    2.5    7.0   
2     a001_s001_e003.mp4       5       9.0      0    0.0    1.0    2.0    7.0   
3     a001_s001_e004.mp4       5      11.0      0    1.0    2.5    6.0   10.0   
4     a001_s001_e005.mp4       5       9.0      0    0.0    1.0    3.0    7.0   
...                  ...     ...       ...    ...    ...    ...    ...    ...   
1507  a018_s014_e002.mp4       5      11.0      0    1.0    3.0    5.0    8.0   
1508  a018_s014_e003.mp4       5      11.0      0    1.0    3.0    5.0    7.5   
1509  a018_s014_e004.mp4       5      10.0      0    1.0    2.5    4.0    6.5   
1510  a018_s014_e005.mp4       5       8.0      0    0.0    1.5    3.0    6.0   
1511  a018_s014_e006.mp4       5       9.0      0    0.0    1.5    3.0    6.0   

      Seg 5  Seg 6  Seg 7  Unnamed: 11  Unnamed: 12  
0       9.0    0.0      0          NaN          NaN  
1      11.0    0.0      0          NaN          NaN  
2       9.0    0.0      0          NaN          NaN  
3      11.0    0.0      0          NaN          NaN  
4       9.0    0.0      0          NaN          NaN  
...     ...    ...    ...          ...          ...  
1507   11.0    0.0      0          NaN          NaN  
1508   11.0    0.0      0          NaN          NaN  
1509   10.0    0.0      0          NaN          NaN  
1510    8.0    0.0      0          NaN          NaN  
1511    9.0    0.0      0          NaN          NaN  

[1512 rows x 13 columns]

In [211]:
mat_tabel[['Seg 1','Seg 2','Seg 3','Seg 4','Seg 5','Seg 6']]

Seg 1  Seg 2  Seg 3  Seg 4  Seg 5  Seg 6
0       0.0    2.0    2.0    7.0    9.0    0.0
1       0.0    1.0    2.5    7.0   11.0    0.0
2       0.0    1.0    2.0    7.0    9.0    0.0
3       1.0    2.5    6.0   10.0   11.0    0.0
4       0.0    1.0    3.0    7.0    9.0    0.0
...     ...    ...    ...    ...    ...    ...
1507    1.0    3.0    5.0    8.0   11.0    0.0
1508    1.0    3.0    5.0    7.5   11.0    0.0
1509    1.0    2.5    4.0    6.5   10.0    0.0
1510    0.0    1.5    3.0    6.0    8.0    0.0
1511    0.0    1.5    3.0    6.0    9.0    0.0

[1512 rows x 6 columns]

In [212]:
mat_tabel.columns

Index(['ID', 'events', 'duration', 'Start', 'Seg 1', 'Seg 2', 'Seg 3', 'Seg 4',
       'Seg 5', 'Seg 6', 'Seg 7', 'Unnamed: 11', 'Unnamed: 12'],
      dtype='object')

In [213]:
mat_tabel = mat_tabel[['Seg 1','Seg 2','Seg 3','Seg 4','Seg 5','Seg 6','Seg 7']]

In [214]:
mat_tabel

Seg 1  Seg 2  Seg 3  Seg 4  Seg 5  Seg 6  Seg 7
0       0.0    2.0    2.0    7.0    9.0    0.0      0
1       0.0    1.0    2.5    7.0   11.0    0.0      0
2       0.0    1.0    2.0    7.0    9.0    0.0      0
3       1.0    2.5    6.0   10.0   11.0    0.0      0
4       0.0    1.0    3.0    7.0    9.0    0.0      0
...     ...    ...    ...    ...    ...    ...    ...
1507    1.0    3.0    5.0    8.0   11.0    0.0      0
1508    1.0    3.0    5.0    7.5   11.0    0.0      0
1509    1.0    2.5    4.0    6.5   10.0    0.0      0
1510    0.0    1.5    3.0    6.0    8.0    0.0      0
1511    0.0    1.5    3.0    6.0    9.0    0.0      0

[1512 rows x 7 columns]

In [215]:
mat_tabel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1512 entries, 0 to 1511
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Seg 1   1512 non-null   float64
 1   Seg 2   1512 non-null   float64
 2   Seg 3   1512 non-null   float64
 3   Seg 4   1512 non-null   float64
 4   Seg 5   1512 non-null   float64
 5   Seg 6   1512 non-null   float64
 6   Seg 7   1512 non-null   int64  
dtypes: float64(6), int64(1)
memory usage: 82.8 KB


In [216]:
mat_numpy = mat_tabel.to_numpy()

In [217]:
mat_numpy

array([[ 0. ,  2. ,  2. , ...,  9. ,  0. ,  0. ],
       [ 0. ,  1. ,  2.5, ..., 11. ,  0. ,  0. ],
       [ 0. ,  1. ,  2. , ...,  9. ,  0. ,  0. ],
       ...,
       [ 1. ,  2.5,  4. , ..., 10. ,  0. ,  0. ],
       [ 0. ,  1.5,  3. , ...,  8. ,  0. ,  0. ],
       [ 0. ,  1.5,  3. , ...,  9. ,  0. ,  0. ]])

In [218]:
mat_numpy.shape

(1512, 7)

In [219]:
# start to end 二维数组
start_to_end_numpy = np.zeros((len(mat_numpy),2))

In [220]:
start_to_end_numpy

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [221]:
for i in range(len(mat_numpy)):
    start_to_end_numpy[i][0] = mat_numpy[i][0]
    k = 6
    while(k>=0 and mat_numpy[i][k]==0):
        k = k - 1   
    if(k==0):
        start_to_end_numpy[i][1] = mat_numpy[i][0]
    else:
        start_to_end_numpy[i][1] = mat_numpy[i][k-1]

In [222]:
start_to_end_numpy

array([[0. , 7. ],
       [0. , 7. ],
       [0. , 7. ],
       ...,
       [1. , 6.5],
       [0. , 6. ],
       [0. , 6. ]])

In [223]:
start_to_end_pandas = pd.DataFrame(start_to_end_numpy)

In [224]:
start_to_end_pandas

0     1
0     0.0   7.0
1     0.0   7.0
2     0.0   7.0
3     1.0  10.0
4     0.0   7.0
...   ...   ...
1507  1.0   8.0
1508  1.0   7.5
1509  1.0   6.5
1510  0.0   6.0
1511  0.0   6.0

[1512 rows x 2 columns]

In [225]:
start_to_end_pandas.isna().sum()

0    0
1    0
dtype: int64

In [226]:
start_to_end_pandas.fillna(axis=0,method='ffill')

0     1
0     0.0   7.0
1     0.0   7.0
2     0.0   7.0
3     1.0  10.0
4     0.0   7.0
...   ...   ...
1507  1.0   8.0
1508  1.0   7.5
1509  1.0   6.5
1510  0.0   6.0
1511  0.0   6.0

[1512 rows x 2 columns]

In [227]:
start_to_end_pandas.isnull().sum()

0    0
1    0
dtype: int64

In [228]:
for i in range(len(start_to_end_numpy)):
    start_to_end_numpy[i][0] = math.floor(start_to_end_numpy[i][0])
    start_to_end_numpy[i][1] = math.floor(start_to_end_numpy[i][1])

In [229]:
num_frame_numpy = np.zeros((len(start_to_end_numpy),2),dtype=int)

In [230]:
num_frame_numpy

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [231]:
for i in range(len(start_to_end_numpy)):
    num_frame_numpy[i][0] = start_to_end_numpy[i][0] * 15
    num_frame_numpy[i][1] = start_to_end_numpy[i][1] * 15

In [232]:
num_frame_numpy

array([[  0, 105],
       [  0, 105],
       [  0, 105],
       ...,
       [ 15,  90],
       [  0,  90],
       [  0,  90]])

In [233]:
num_frame_numpy.dtype

dtype('int32')

In [234]:
mat_path = os.path.join(folder_path,mat_list[0])

In [235]:
mat_path

'E:\\GitProjects\\Video-Captioning\\PDVC数据处理\\WorkoutUOW-18-skeleton\\a001_s001_e001.mat'

In [236]:
mat = io.loadmat(mat_path)

In [237]:
mat = mat['one_sample']

In [238]:
mat

array([[-4.43254458e-03,  6.26969635e-02,  3.07751274e+00, ...,
         1.19806148e-01, -7.38110483e-01,  3.10789037e+00],
       [-1.86426775e-03,  6.23902455e-02,  3.07780027e+00, ...,
         1.19443282e-01, -7.39387155e-01,  3.10847569e+00],
       [ 5.21074631e-04,  6.25513270e-02,  3.07817936e+00, ...,
         1.20068751e-01, -7.41531968e-01,  3.10954523e+00],
       ...,
       [-5.61582074e-02,  5.32767400e-02,  3.05065727e+00, ...,
         1.10598259e-01, -7.32131541e-01,  3.10978627e+00],
       [-5.48236482e-02,  5.34168333e-02,  3.04868913e+00, ...,
         1.10811770e-01, -7.32616305e-01,  3.10978365e+00],
       [-5.16514257e-02,  5.28396145e-02,  3.04643106e+00, ...,
         1.11337095e-01, -7.36358404e-01,  3.10856867e+00]])

In [239]:
mat = mat[num_frame_numpy[0][0]:num_frame_numpy[0][1],:]

In [240]:
mat.shape

(105, 60)

In [241]:
mat = mat.reshape(int(mat.shape[0]/15),900)

In [242]:
mat.shape

(7, 900)

In [243]:
save_folder_path = "E:\GitProjects\Video-Captioning\PDVC数据处理"

In [244]:
matFileName1 = "v_a001"
matFileName2 = "_s001"
matFileName3 = "_e001"
matFileName4 = ".npy"

In [245]:
matFileName = matFileName1 + matFileName2 + matFileName3 + matFileName4

In [246]:
matFileName

'v_a001_s001_e001.npy'

In [247]:
save_path = os.path.join(save_folder_path,matFileName)

In [248]:
save_path

'E:\\GitProjects\\Video-Captioning\\PDVC数据处理\\v_a001_s001_e001.npy'

In [249]:
# np.save(save_path,mat)

In [250]:
test = np.load("./v_a001_s001_e001.npy")

In [251]:
test

array([[-0.11270361,  0.06827112,  3.22379327, ...,  0.13506693,
        -0.68121147,  3.24574518],
       [-0.11928986,  0.10805017,  3.22128725, ...,  0.12881841,
        -0.67988831,  3.24503374],
       [-0.09980473,  0.17106898,  3.22275949, ...,  0.12412241,
        -0.69055319,  3.24873209],
       ...,
       [-0.13860944,  0.15050018,  3.20698476, ...,  0.12975925,
        -0.67541796,  3.24410295],
       [-0.14826706,  0.126698  ,  3.19271493, ...,  0.12813897,
        -0.66341549,  3.251688  ],
       [-0.15815303, -0.0260425 ,  3.2357161 , ...,  0.13348016,
        -0.67711389,  3.24922609]])

In [252]:
test.shape

(7, 900)

In [253]:
save_folder_path = r"E:\GitProjects\Video-Captioning\PDVC数据处理\new_data"

In [254]:
save_folder_path

'E:\\GitProjects\\Video-Captioning\\PDVC数据处理\\new_data'

In [265]:
matFileName1 = "v_a0"
matFileName2 = "_s00"
matFileName3 = "_e00"
matFileName4 = ".npy"

In [266]:
mat_load_path = os.path.join(folder_path,mat_list[0])
mat = io.loadmat(mat_load_path)
mat = mat['one_sample']
mat = mat[num_frame_numpy[0][0]:num_frame_numpy[0][1],:]

In [267]:
for i in range(18):
    if(i<9):
        matFileName1+="0"
    matFileName1 = matFileName1 + str(i+1) 
    for j in range(14):
        matFileName2 = matFileName2 + str(j+1)
        for k in range(6):
            matFileName3 = matFileName3 + str(k+1) 
            matFileName = matFileName1 + matFileName2 + matFileName3 + matFileName4

            idx = i*84 + j*6 + k
            mat_load_path = os.path.join(folder_path,mat_list[idx])
            mat = io.loadmat(mat_load_path)
            mat = mat['one_sample']
            mat = mat[num_frame_numpy[idx][0]:num_frame_numpy[idx][1],:]

            mat_save_path = os.path.join(save_folder_path,matFileName)
            np.save(mat_save_path,mat)

            matFileName3 = "_e00"        
        matFileName2 = "_s00"
    matFileName1 = "v_a0"